// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Discount struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	Label          string    `json:"label"`
	ExpirationTime time.Time `json:"expiration_time"`
	Code           string    `json:"code"`
	Status         bool      `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID              int64          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	PhoneNumber     string         `json:"phone_number"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	DeviceID        string         `json:"device_id"`
	LastLogin       sql.NullTime   `json:"last_login"`
	LoginAttempt    sql.NullInt32  `json:"login_attempt"`
	Status          sql.NullString `json:"status"`
	IsEmailVerified string         `json:"is_email_verified"`
	CreatedAt       time.Time      `json:"created_at"`
	LastUpdatedAt   sql.NullTime   `json:"last_updated_at"`
	IsDeleted       sql.NullBool   `json:"is_deleted"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullInt64  `json:"deleted_by"`
}

type UserDeviceList struct {
	ID            int64        `json:"id"`
	UserID        int64        `json:"user_id"`
	DeviceID      string       `json:"device_id"`
	IpAddress     string       `json:"ip_address"`
	ClientDetails string       `json:"client_details"`
	IsBlocked     sql.NullBool `json:"is_blocked"`
	CreatedAt     time.Time    `json:"created_at"`
}

type UserSession struct {
	ID           int64     `json:"id"`
	SessionID    uuid.UUID `json:"session_id"`
	UserID       int64     `json:"user_id"`
	Token        string    `json:"token"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	Ip           string    `json:"ip"`
	Channel      string    `json:"channel"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
