// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDiscount(ctx context.Context, arg AddDiscountParams) (Discount, error)
	AddUserDevice(ctx context.Context, arg AddUserDeviceParams) (UserDeviceList, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserByUUIDRow, error)
	GetUserDiscountByUserID(ctx context.Context, userID int64) (Discount, error)
	GetUserSessionByUserID(ctx context.Context, userID int64) (UserSession, error)
	UpdateUserDevice(ctx context.Context, arg UpdateUserDeviceParams) (UpdateUserDeviceRow, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserFirstName(ctx context.Context, arg UpdateUserFirstNameParams) (UpdateUserFirstNameRow, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) (UpdateUserLastLoginRow, error)
	UpdateUserLastName(ctx context.Context, arg UpdateUserLastNameParams) (UpdateUserLastNameRow, error)
	UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (UpdateUserPhoneNumberRow, error)
	UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) (UserSession, error)
}

var _ Querier = (*Queries)(nil)
